/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/home_office/scene.gltf')
  console.log('nodes: ', nodes);
  console.log('materials: ', materials);
  const objectMeshes = Object.keys(nodes)
    .filter((key) => key.startsWith('Object_'))
    .map((key) => (
      <mesh
        key={key}
        castShadow
        receiveShadow
        geometry={nodes[key].geometry}
        material={materials[nodes[key].material.name]}
      />
    ));
  
  return (
    <group ref={groupRef} {...props} dispose={null}>
      {/*
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['Material.003']}
        />
      */}
      {objectMeshes}
    </group>
  )
}

useGLTF.preload('/home_office/scene.gltf')
